#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

NAME="homebridge"
BUNDLE="/mnt/X6/UXC/homebridge/bundle"


start_service()
{
        [ -z "$1" ] || true

        logger -t homebridge_init "Waiting for /mnt/X6..."

        while ! mountpoint -q /mnt/X6; do
                sleep 2
        done

        logger -t homebridge_init "/mnt/X6 mounted."

        if ! uxc state "$NAME" >/dev/null 2>&1; then
                logger -t homebridge_init "Creating UXC container..."

                uxc create "$NAME" \
                    --bundle "$BUNDLE" \
                    --mounts /mnt/X6
        fi


        if uxc list | grep -q "$NAME.*running"; then
                logger -t homebridge_init "Homebridge already running."
                return
        fi


        logger -t homebridge_init "Starting Homebridge container..."

        uxc start "$NAME"

        sleep 5


        if uxc list | grep -q "$NAME.*running"; then
                logger -t homebridge_init "Homebridge started successfully."
        else
                logger -t homebridge_init "Homebridge failed to start."
        fi
}


stop_service()
{
        logger -t homebridge_init "Stopping Homebridge..."

        uxc stop "$NAME" 2>/dev/null || true
}


restart()
{
        stop_service
        sleep 3
        start_service
}


service_triggers()
{
        procd_add_reload_trigger "homebridge"
}